defaults:
  - _self_
  - algorithm: ia2c
  - logger: filesystemlogger
  - override hydra/job_logging: file
  - override hydra/launcher: submitit_local
  
hydra:
  run:
    dir: outputs/${env.name}/${algorithm.name}/${random:4}
  launcher:
    timeout_min: 2880
    cpus_per_task: 1
    mem_gb: 4
  job:
    chdir: True

seed: null

algorithm:
  total_steps: 100
  log_interval: 10
  save_interval: 100
  eval_interval: 10
  eval_episodes: 100
  video_interval: False
  video_frames: 500

env:
  _target_: utils.envs.make_env
  name : lux_marl:LuxAIMARLEnv
  time_limit : 5
  clear_info: False
  observe_id: False
  standardise_rewards: False
  parallel_envs: 10 
  wrappers:
  - FlattenObservation
